/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_boco_whl_funddemo_module_activity_thirdlib_ffmpeg_HelloJni */

#ifndef _Included_com_boco_whl_funddemo_module_activity_thirdlib_ffmpeg_HelloJni
#define _Included_com_boco_whl_funddemo_module_activity_thirdlib_ffmpeg_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_boco_whl_funddemo_module_activity_thirdlib_ffmpeg_HelloJni
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_boco_whl_funddemo_module_activity_thirdlib_ffmpeg_HelloJni_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_boco_whl_funddemo_module_activity_thirdlib_ffmpeg_HelloJni
 * Method:    unimplementedStringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_boco_whl_funddemo_module_activity_thirdlib_ffmpeg_HelloJni_unimplementedStringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
